# Copyright (c) 2024 Mike Tsao

[workspace.package]
authors = ["Mike Tsao <mike@sowbug.com>"]
documentation = "https://docs.rs/ensnare/"
edition = "2021"
homepage = "https://github.com/ensnare-org/ensnare"
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/ensnare-org/ensnare"
version = "0.0.2-alpha.14"

[package]
name = "ensnare"
description = "A library for generating digital audio"
keywords = ["audio", "music"]
readme.workspace = true
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
anyhow = { version = "1.0.86", default-features = false }
byteorder = "1.5.0"
cpal = { version = "0.15.3", optional = true }
crossbeam = "0.8.4"
delegate = "0.12.0"
derivative = { version = "2.2.0", features = ["use_core"] }
derive_builder = "0.20.0"
derive_more = "0.99.17"
eframe = { version = "0.27", optional = true }
ensnare-proc-macros = { version = "0.0.5", path = "crates/proc-macros" }
getrandom = { version = "0.2.12", features = [] }
midly = "0.5.3"
nonoverlapping_interval_tree = "0.1.5"
oorandom = "11.1.3"
rustc-hash = "1.1.0"
serde = { version = "1.0.203", features = ["rc", "derive"] }
strum = "0.26.2"
strum_macros = "0.26.2"
synonym = "0.1.3"
typetag = "0.2.16"

[dev-dependencies]
clap = { version = "4.5.4", features = ["derive"] }

[features]
default = ["std"]
cpal = ["dep:cpal"]
std = ["getrandom/std", "anyhow/std"]
egui = ["eframe"]

[workspace]
members = ["crates/proc-macros", "crates/services"]
